[package]
edition = "2018"
name = "show-notes"
# Version will match released show number! Episode 12 will be `0.1.2`.
version = "0.3.1"
authors = ["Chris Krycho <chris@chriskrycho.com>"]

[dependencies]
regex = "1"
libc = "0.2"

[build-dependencies]
cc = "1.0"

[lib]
crate-type = ["cdylib"]
